"""Behavior tests for backend-upgrade validation plans."""

from __future__ import annotations

import copy
import unittest

from scripts.check_backend_validation import render_backend_validation_markdown, validate_backend_validation_plan


def _smoke_record(
    record_id: str = "optimizer-proof",
    *,
    backend: str = "trainer-a",
    evidence_kind: str = "real-optimizer-step",
    outcome: str = "passed",
) -> dict[str, object]:
    return {
        "id": record_id,
        "backend": backend,
        "adapter_source": {"kind": "git-commit", "value": "adapter"},
        "runtime_image": {"kind": "digest", "value": "sha256:image"},
        "native_path": {"entrypoint": "train.py", "recovery": "completed"},
        "evidence_kind": evidence_kind,
        "outcome": outcome,
    }


def _contract(
    contract_id: str = "family-a-image",
    *,
    change_ids: list[str] | None = None,
    family: str = "family-a",
    mode: str = "text-to-image",
    dataset_kind: str = "image",
    disposition: str = "support",
) -> dict[str, object]:
    return {
        "id": contract_id,
        "change_ids": change_ids or ["added-family-a"],
        "backend": "trainer-a",
        "family": family,
        "variant": "base",
        "mode": mode,
        "dataset": {"kind": dataset_kind, "conditioning": "none"},
        "execution": {
            "adapter": "generic",
            "entrypoints": ["train.py"],
            "model_roles": ["transformer", "text_encoder", "vae"],
            "cache_stages": ["latents"],
            "output": "lora-safetensors",
            "lifecycle_changed": False,
        },
        "disposition": disposition,
        "evidence": {
            "source": ["upstream:commit-a"],
            "compile": [
                "tests/test_backend_validation_check.py::"
                "BackendValidationCheckTests."
                "test_complete_supported_contract_accepts_compile_and_image_evidence_with_visible_runtime_note"
            ],
            "image": ["optimizer-proof"],
            "optimizer": ["optimizer-proof"],
            "lifecycle": [],
        },
    }


def _plan(*, status: str = "complete") -> dict[str, object]:
    return {
        "schema_version": 1,
        "upgrade": {
            "id": "trainer-a-upgrade",
            "status": status,
            "backends": [
                {
                    "name": "trainer-a",
                    "from": {"kind": "git-commit", "value": "old"},
                    "to": {"kind": "git-commit", "value": "new"},
                    "source_refs": ["upstream:old..new"],
                }
            ],
        },
        "changes": [
            {
                "id": "added-family-a",
                "backend": "trainer-a",
                "summary": "Added family A",
                "kind": "execution-contract",
                "source_refs": ["upstream:commit-a"],
            }
        ],
        "contracts": [_contract()],
    }


class BackendValidationCheckTests(unittest.TestCase):
    def test_markdown_renderer_exposes_every_contract_and_evidence_level(self) -> None:
        plan = _plan(status="in_progress")
        plan["contracts"][0]["gap"] = "Needs optimizer | lifecycle proof.\nDo not promote yet."
        plan["contracts"].append({
            "id": "family-a-audio",
            "change_ids": ["added-family-a"],
            "backend": "trainer-a",
            "family": "family-a",
            "variant": "audio",
            "mode": "text-to-audio",
            "dataset": {"kind": "audio", "conditioning": "target audio"},
            "disposition": "unsupported",
            "missing_capability": "No audio artifact contract.",
            "evidence": {"source": ["upstream:commit-a"]},
        })

        rendered = render_backend_validation_markdown(plan, "example.yaml")

        self.assertIn("Generated from `example.yaml`; do not edit this file by hand.", rendered)
        self.assertIn("2 contracts: 1 support, 1 unsupported, 0 not applicable", rendered)
        self.assertIn("✅ runtime verified", rendered)
        self.assertIn("⛔ unsupported", rendered)
        self.assertIn("| family-a-image | trainer-a | family-a / base | text-to-image | image / none | ✅ runtime verified |", rendered)
        self.assertIn("🧩 compile 1 · 📦 image 1 · 🔥 optimizer 1 · ♻️ lifecycle 0", rendered)
        self.assertIn("Needs optimizer \\| lifecycle proof. Do not promote yet.", rendered)
        self.assertIn("No audio artifact contract.", rendered)

    def test_markdown_renderer_marks_supported_contracts_waiting_for_runtime(self) -> None:
        plan = _plan(status="in_progress")
        plan["contracts"][0]["evidence"]["optimizer"] = []
        plan["contracts"][0]["runtime_note"] = "Real optimizer execution is not yet observed."

        rendered = render_backend_validation_markdown(plan, "example.yaml")

        self.assertIn("🧪 compile/image verified", rendered)
        self.assertIn("Real optimizer execution is not yet observed.", rendered)

    def test_complete_supported_contract_accepts_compile_and_image_evidence_with_visible_runtime_note(self) -> None:
        plan = _plan()
        plan["contracts"][0]["evidence"]["optimizer"] = []
        plan["contracts"][0]["runtime_note"] = "Real optimizer execution has not been observed."

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertEqual(failures, [])

    def test_in_progress_contract_may_keep_an_explicit_gap(self) -> None:
        plan = _plan(status="in_progress")
        plan["contracts"][0]["evidence"]["compile"] = []
        plan["contracts"][0]["gap"] = "Compile projection is not implemented."

        self.assertEqual(validate_backend_validation_plan(plan, [_smoke_record()]), [])

    def test_supported_contract_without_optimizer_evidence_requires_runtime_note(self) -> None:
        plan = _plan(status="complete")
        plan["contracts"][0]["evidence"]["optimizer"] = []

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("runtime_note is required" in failure for failure in failures), failures)

    def test_every_inventory_change_must_be_classified(self) -> None:
        plan = _plan(status="in_progress")
        plan["changes"].append(
            {
                "id": "changed-cache",
                "backend": "trainer-a",
                "summary": "Changed cache format",
                "kind": "execution-contract",
                "source_refs": ["upstream:commit-b"],
            }
        )

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("changed-cache" in failure and "not classified" in failure for failure in failures), failures)

    def test_representative_evidence_cannot_cross_an_execution_contract(self) -> None:
        plan = _plan()
        second = _contract(
            "family-a-video",
            family="family-a",
            mode="text-to-video",
            dataset_kind="video",
        )
        second["covered_by"] = "family-a-image"
        second["coverage_rationale"] = "The same backend code is used."
        second["evidence"]["optimizer"] = []
        plan["contracts"].append(second)

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("execution contract differs" in failure for failure in failures), failures)

    def test_coverage_cycles_are_rejected(self) -> None:
        plan = _plan()
        second = copy.deepcopy(plan["contracts"][0])
        second["id"] = "family-a-alias"
        second["covered_by"] = "family-a-image"
        second["coverage_rationale"] = "Identical native execution contract."
        plan["contracts"][0]["covered_by"] = "family-a-alias"
        plan["contracts"][0]["coverage_rationale"] = "Identical native execution contract."
        plan["contracts"].append(second)

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("coverage cycle" in failure for failure in failures), failures)

    def test_optimizer_reference_must_be_passed_real_evidence_for_the_backend(self) -> None:
        plan = _plan()

        failures = validate_backend_validation_plan(
            plan,
            [_smoke_record(backend="trainer-b", evidence_kind="image", outcome="failed")],
        )

        self.assertTrue(any("passed real-optimizer-step" in failure for failure in failures), failures)

    def test_compile_reference_must_name_an_existing_test(self) -> None:
        plan = _plan()
        plan["contracts"][0]["evidence"]["compile"] = ["tests/not_real.py::test_claim"]

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("compile reference" in failure and "does not exist" in failure for failure in failures), failures)

    def test_image_reference_must_name_passed_identity_bound_smoke(self) -> None:
        plan = _plan()
        plan["contracts"][0]["evidence"]["image"] = ["unrecorded-image-smoke"]

        failures = validate_backend_validation_plan(plan, [_smoke_record()])

        self.assertTrue(any("image reference" in failure and "identity-bound" in failure for failure in failures), failures)

    def test_lifecycle_reference_must_name_passed_runtime_evidence(self) -> None:
        plan = _plan()
        plan["contracts"][0]["execution"]["lifecycle_changed"] = True
        plan["contracts"][0]["evidence"]["lifecycle"] = ["parser-only"]

        failures = validate_backend_validation_plan(
            plan,
            [_smoke_record(), _smoke_record("parser-only", evidence_kind="parser")],
        )

        self.assertTrue(any("lifecycle reference" in failure and "runtime evidence" in failure for failure in failures), failures)

    def test_complete_plan_accepts_supported_and_explicitly_unsupported_changes(self) -> None:
        plan = _plan()
        plan["changes"].append(
            {
                "id": "added-audio-mode",
                "backend": "trainer-a",
                "summary": "Added audio training",
                "kind": "execution-contract",
                "source_refs": ["upstream:commit-c"],
            }
        )
        unsupported = _contract(
            "family-a-audio",
            change_ids=["added-audio-mode"],
            mode="text-to-audio",
            dataset_kind="audio",
            disposition="unsupported",
        )
        unsupported["missing_capability"] = "Kura has no audio dataset or artifact contract."
        unsupported["evidence"] = {"source": ["upstream:commit-c"]}
        plan["contracts"].append(unsupported)

        self.assertEqual(
            validate_backend_validation_plan(plan, [_smoke_record()]),
            [],
        )


if __name__ == "__main__":
    unittest.main()
