#!/usr/bin/env python3
"""Validate backend-upgrade inventories and their evidence coverage."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
PLAN_DIR = ROOT / "docs" / "backend-validation"
SMOKE_PATH = ROOT / "docs" / "backend-smoke-evidence.yaml"
IDENTITY_KEYS = {"kind", "value"}
UPGRADE_STATUSES = {"in_progress", "complete"}
CHANGE_KINDS = {"execution-contract", "enhancement", "outside-contract"}
DISPOSITIONS = {"support", "unsupported", "not_applicable"}
ADAPTER_KINDS = {"built-in", "generic", "escape-hatch"}
EXECUTION_LIST_KEYS = ("entrypoints", "model_roles", "cache_stages")


def _markdown_cell(value: object) -> str:
    text = "" if value is None else str(value)
    return " ".join(text.split()).replace("|", "\\|")


def _contract_status(contract: dict[str, Any], evidence: dict[str, Any]) -> str:
    disposition = contract.get("disposition")
    if disposition == "unsupported":
        return "⛔ unsupported"
    if disposition == "not_applicable":
        return "➖ not applicable"
    optimizer = evidence.get("optimizer")
    lifecycle = evidence.get("lifecycle")
    execution = contract.get("execution") if isinstance(contract.get("execution"), dict) else {}
    runtime_verified = bool(contract.get("covered_by")) or isinstance(optimizer, list) and bool(optimizer)
    lifecycle_verified = execution.get("lifecycle_changed") is not True or isinstance(lifecycle, list) and bool(lifecycle)
    return "✅ runtime verified" if runtime_verified and lifecycle_verified else "🧪 compile/image verified"


def render_backend_validation_markdown(plan: dict[str, Any], source: str) -> str:
    """Render the human review table without creating a second source of truth."""

    upgrade = plan.get("upgrade") if isinstance(plan.get("upgrade"), dict) else {}
    contracts = plan.get("contracts") if isinstance(plan.get("contracts"), list) else []
    counts = {disposition: 0 for disposition in DISPOSITIONS}
    for contract in contracts:
        if isinstance(contract, dict) and contract.get("disposition") in counts:
            counts[str(contract["disposition"])] += 1
    lines = [
        f"# Backend validation: {_markdown_cell(upgrade.get('id') or 'unnamed upgrade')}",
        "",
        f"Generated from `{_markdown_cell(source)}`; do not edit this file by hand.",
        "",
        f"Status: {'✅' if upgrade.get('status') == 'complete' else '🟡'} "
        f"`{_markdown_cell(upgrade.get('status') or 'unknown')}`. "
        f"{len(contracts)} contracts: {counts['support']} support, "
        f"{counts['unsupported']} unsupported, {counts['not_applicable']} not applicable.",
        "",
        "Legend: ✅ real runtime verified · 🧪 supported by upstream and compile/image verified; "
        "real optimizer not yet observed · "
        "⛔ unsupported · ➖ not applicable",
        "",
        "Evidence: 🧩 compile · 📦 pinned-image entrypoint · 🔥 real optimizer · ♻️ lifecycle",
        "",
        "| Contract | Backend | Family / variant | Mode | Dataset / conditioning | Status | Evidence | Evidence note or rationale |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for raw_contract in contracts:
        contract = raw_contract if isinstance(raw_contract, dict) else {}
        dataset = contract.get("dataset") if isinstance(contract.get("dataset"), dict) else {}
        evidence = contract.get("evidence") if isinstance(contract.get("evidence"), dict) else {}
        evidence_summary = " · ".join(
            f"{icon} {level} {len(evidence.get(level, [])) if isinstance(evidence.get(level), list) else 0}"
            for icon, level in (("🧩", "compile"), ("📦", "image"), ("🔥", "optimizer"), ("♻️", "lifecycle"))
        )
        if contract.get("covered_by"):
            evidence_summary += f"; covered by: {contract['covered_by']}"
        explanation = (
            contract.get("gap")
            or contract.get("runtime_note")
            or contract.get("missing_capability")
            or contract.get("rationale")
            or "—"
        )
        cells = (
            contract.get("id"),
            contract.get("backend"),
            f"{contract.get('family', '')} / {contract.get('variant', '')}",
            contract.get("mode"),
            f"{dataset.get('kind', '')} / {dataset.get('conditioning', '')}",
            _contract_status(contract, evidence),
            evidence_summary,
            explanation,
        )
        lines.append("| " + " | ".join(_markdown_cell(cell) for cell in cells) + " |")
    lines.append("")
    return "\n".join(lines)


def _nonempty_string(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _nonempty_string_list(value: object) -> bool:
    return isinstance(value, list) and bool(value) and all(_nonempty_string(item) for item in value)


def _contract_signature(contract: dict[str, Any]) -> tuple[object, ...]:
    dataset = contract.get("dataset") if isinstance(contract.get("dataset"), dict) else {}
    execution = contract.get("execution") if isinstance(contract.get("execution"), dict) else {}
    return (
        contract.get("backend"),
        contract.get("family"),
        contract.get("mode"),
        dataset.get("kind"),
        dataset.get("conditioning"),
        execution.get("adapter"),
        tuple(execution.get("entrypoints", [])) if isinstance(execution.get("entrypoints"), list) else None,
        tuple(execution.get("model_roles", [])) if isinstance(execution.get("model_roles"), list) else None,
        tuple(execution.get("cache_stages", [])) if isinstance(execution.get("cache_stages"), list) else None,
        execution.get("output"),
        execution.get("lifecycle_changed"),
    )


def _identity_bound_passed_record(
    record: dict[str, object] | None,
    backend: object,
    kinds: set[str],
) -> bool:
    if not record or record.get("backend") != backend or record.get("outcome") != "passed":
        return False
    if record.get("evidence_kind") not in kinds:
        return False
    for key in ("adapter_source", "runtime_image"):
        identity = record.get(key)
        if not isinstance(identity, dict) or not IDENTITY_KEYS <= set(identity):
            return False
    return isinstance(record.get("native_path"), dict) and bool(record["native_path"])


def validate_backend_validation_plan(
    plan: object,
    smoke_records: list[object],
    *,
    source: str = "plan",
) -> list[str]:
    """Return human-readable contract failures without mutating the plan."""

    failures: list[str] = []
    if not isinstance(plan, dict):
        return [f"{source}: plan must be a mapping"]
    if plan.get("schema_version") != 1:
        failures.append(f"{source}: schema_version must be 1")

    upgrade = plan.get("upgrade")
    if not isinstance(upgrade, dict):
        failures.append(f"{source}: upgrade must be a mapping")
        upgrade = {}
    status = upgrade.get("status")
    if status not in UPGRADE_STATUSES:
        failures.append(f"{source}: upgrade.status must be one of {sorted(UPGRADE_STATUSES)}")
    if not _nonempty_string(upgrade.get("id")):
        failures.append(f"{source}: upgrade.id must be a non-empty string")
    backends = upgrade.get("backends")
    backend_names: set[str] = set()
    if not isinstance(backends, list) or not backends:
        failures.append(f"{source}: upgrade.backends must be a non-empty list")
        backends = []
    for index, backend in enumerate(backends):
        label = f"{source}: upgrade.backends[{index}]"
        if not isinstance(backend, dict):
            failures.append(f"{label} must be a mapping")
            continue
        name = backend.get("name")
        if not _nonempty_string(name) or name in backend_names:
            failures.append(f"{label}.name must be a unique non-empty string")
        else:
            backend_names.add(name)
        for identity_name in ("from", "to"):
            identity = backend.get(identity_name)
            if not isinstance(identity, dict) or not IDENTITY_KEYS <= set(identity):
                failures.append(f"{label}.{identity_name} requires kind and value")
        if not _nonempty_string_list(backend.get("source_refs")):
            failures.append(f"{label}.source_refs must be a non-empty string list")

    changes = plan.get("changes")
    if not isinstance(changes, list) or not changes:
        failures.append(f"{source}: changes must be a non-empty list")
        changes = []
    change_ids: set[str] = set()
    for index, change in enumerate(changes):
        label = f"{source}: changes[{index}]"
        if not isinstance(change, dict):
            failures.append(f"{label} must be a mapping")
            continue
        change_id = change.get("id")
        if not _nonempty_string(change_id) or change_id in change_ids:
            failures.append(f"{label}.id must be a unique non-empty string")
        else:
            change_ids.add(change_id)
        if change.get("backend") not in backend_names:
            failures.append(f"{label}.backend must name an upgrade backend")
        if not _nonempty_string(change.get("summary")):
            failures.append(f"{label}.summary must be a non-empty string")
        if change.get("kind") not in CHANGE_KINDS:
            failures.append(f"{label}.kind must be one of {sorted(CHANGE_KINDS)}")
        if not _nonempty_string_list(change.get("source_refs")):
            failures.append(f"{label}.source_refs must be a non-empty string list")

    records_by_id: dict[str, dict[str, object]] = {}
    for record in smoke_records:
        if isinstance(record, dict) and _nonempty_string(record.get("id")):
            records_by_id[str(record["id"])] = record

    contracts = plan.get("contracts")
    if not isinstance(contracts, list) or not contracts:
        failures.append(f"{source}: contracts must be a non-empty list")
        contracts = []
    contracts_by_id: dict[str, dict[str, Any]] = {}
    classified_change_ids: set[str] = set()
    for index, contract in enumerate(contracts):
        label = f"{source}: contracts[{index}]"
        if not isinstance(contract, dict):
            failures.append(f"{label} must be a mapping")
            continue
        contract_id = contract.get("id")
        if not _nonempty_string(contract_id) or contract_id in contracts_by_id:
            failures.append(f"{label}.id must be a unique non-empty string")
        else:
            contracts_by_id[str(contract_id)] = contract
        references = contract.get("change_ids")
        if not _nonempty_string_list(references):
            failures.append(f"{label}.change_ids must be a non-empty string list")
            references = []
        for change_id in references:
            if change_id not in change_ids:
                failures.append(f"{label}.change_ids references unknown change {change_id!r}")
            else:
                classified_change_ids.add(change_id)
        if contract.get("backend") not in backend_names:
            failures.append(f"{label}.backend must name an upgrade backend")
        for key in ("family", "variant", "mode"):
            if not _nonempty_string(contract.get(key)):
                failures.append(f"{label}.{key} must be a non-empty string")
        dataset = contract.get("dataset")
        if not isinstance(dataset, dict):
            failures.append(f"{label}.dataset must be a mapping")
        else:
            for key in ("kind", "conditioning"):
                if not _nonempty_string(dataset.get(key)):
                    failures.append(f"{label}.dataset.{key} must be a non-empty string")
        disposition = contract.get("disposition")
        if disposition not in DISPOSITIONS:
            failures.append(f"{label}.disposition must be one of {sorted(DISPOSITIONS)}")
            continue
        evidence = contract.get("evidence")
        if not isinstance(evidence, dict):
            failures.append(f"{label}.evidence must be a mapping")
            evidence = {}
        if not _nonempty_string_list(evidence.get("source")):
            failures.append(f"{label} requires source evidence")

        gap = contract.get("gap")
        if gap is not None and not _nonempty_string(gap):
            failures.append(f"{label}.gap must be a non-empty string when present")
        runtime_note = contract.get("runtime_note")
        if runtime_note is not None and not _nonempty_string(runtime_note):
            failures.append(f"{label}.runtime_note must be a non-empty string when present")
        if status == "complete" and gap is not None:
            failures.append(f"{label}: a complete upgrade cannot retain a gap")

        if disposition == "support":
            execution = contract.get("execution")
            if not isinstance(execution, dict):
                failures.append(f"{label}.execution must be a mapping for support")
                execution = {}
            if execution.get("adapter") not in ADAPTER_KINDS:
                failures.append(f"{label}.execution.adapter must be one of {sorted(ADAPTER_KINDS)}")
            for key in EXECUTION_LIST_KEYS:
                value = execution.get(key)
                if not isinstance(value, list) or not all(_nonempty_string(item) for item in value):
                    failures.append(f"{label}.execution.{key} must be a string list")
            if not _nonempty_string(execution.get("output")):
                failures.append(f"{label}.execution.output must be a non-empty string")
            if not isinstance(execution.get("lifecycle_changed"), bool):
                failures.append(f"{label}.execution.lifecycle_changed must be boolean")
            missing_levels: list[str] = []
            for level in ("compile", "image"):
                if not _nonempty_string_list(evidence.get(level)):
                    missing_levels.append(f"{level} evidence")
            covered_by = contract.get("covered_by")
            if (
                covered_by is None
                and not _nonempty_string_list(evidence.get("optimizer"))
                and not _nonempty_string(runtime_note)
            ):
                failures.append(f"{label}.runtime_note is required until real optimizer evidence exists")
            if execution.get("lifecycle_changed") is True and not _nonempty_string_list(evidence.get("lifecycle")):
                missing_levels.append("lifecycle evidence")
            if missing_levels and not (status == "in_progress" and _nonempty_string(gap)):
                failures.append(f"{label} missing {', '.join(missing_levels)}")
            compile_refs = evidence.get("compile", [])
            if isinstance(compile_refs, list):
                for reference in compile_refs:
                    if not isinstance(reference, str) or "::" not in reference:
                        failures.append(f"{label} compile reference {reference!r} must use path::test-symbol")
                        continue
                    relative_path, symbol = reference.split("::", 1)
                    test_path = ROOT / relative_path
                    if not test_path.is_file():
                        failures.append(f"{label} compile reference path does not exist: {relative_path}")
                    elif not symbol or symbol.split(".")[-1] not in test_path.read_text(encoding="utf-8"):
                        failures.append(f"{label} compile reference symbol does not exist: {reference}")
            image_refs = evidence.get("image", [])
            if isinstance(image_refs, list):
                for record_id in image_refs:
                    record = records_by_id.get(record_id) if isinstance(record_id, str) else None
                    if not _identity_bound_passed_record(
                        record,
                        contract.get("backend"),
                        {"parser", "real-runtime", "real-optimizer-step"},
                    ):
                        failures.append(
                            f"{label} image reference {record_id!r} must name passed, "
                            "identity-bound smoke evidence for the same backend"
                        )
            optimizer_refs = evidence.get("optimizer", [])
            if isinstance(optimizer_refs, list):
                for record_id in optimizer_refs:
                    record = records_by_id.get(record_id) if isinstance(record_id, str) else None
                    if not _identity_bound_passed_record(
                        record,
                        contract.get("backend"),
                        {"real-optimizer-step"},
                    ):
                        failures.append(
                            f"{label} optimizer reference {record_id!r} must name passed "
                            "real-optimizer-step evidence for the same backend"
                        )
            lifecycle_refs = evidence.get("lifecycle", [])
            if isinstance(lifecycle_refs, list):
                for record_id in lifecycle_refs:
                    record = records_by_id.get(record_id) if isinstance(record_id, str) else None
                    if not _identity_bound_passed_record(
                        record,
                        contract.get("backend"),
                        {"real-runtime", "real-optimizer-step"},
                    ):
                        failures.append(
                            f"{label} lifecycle reference {record_id!r} must name passed, "
                            "identity-bound runtime evidence for the same backend"
                        )
        elif disposition == "unsupported":
            if not _nonempty_string(contract.get("missing_capability")):
                failures.append(f"{label}.missing_capability is required for unsupported contracts")
        elif not _nonempty_string(contract.get("rationale")):
            failures.append(f"{label}.rationale is required for not_applicable contracts")

    for change_id in sorted(change_ids - classified_change_ids):
        failures.append(f"{source}: change {change_id!r} is not classified by any contract")

    coverage_edges: dict[str, str] = {}
    for contract_id, contract in contracts_by_id.items():
        covered_by = contract.get("covered_by")
        if covered_by is None:
            continue
        label = f"{source}: contract {contract_id!r}"
        if not _nonempty_string(covered_by) or covered_by not in contracts_by_id:
            failures.append(f"{label}.covered_by must reference another contract")
            continue
        if not _nonempty_string(contract.get("coverage_rationale")):
            failures.append(f"{label}.coverage_rationale is required")
        target = contracts_by_id[str(covered_by)]
        if contract.get("disposition") != "support" or target.get("disposition") != "support":
            failures.append(f"{label}: representative coverage applies only between supported contracts")
        if _contract_signature(contract) != _contract_signature(target):
            failures.append(f"{label}: covered_by execution contract differs from {covered_by!r}")
        coverage_edges[contract_id] = str(covered_by)

    for start in coverage_edges:
        seen: set[str] = set()
        current = start
        while current in coverage_edges:
            if current in seen:
                failures.append(f"{source}: coverage cycle includes contract {current!r}")
                break
            seen.add(current)
            current = coverage_edges[current]

    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the human-readable Markdown tables after validating their YAML sources",
    )
    args = parser.parse_args(argv)
    smoke_payload = yaml.safe_load(SMOKE_PATH.read_text(encoding="utf-8"))
    smoke_records = smoke_payload.get("records", []) if isinstance(smoke_payload, dict) else []
    failures: list[str] = []
    paths = sorted(PLAN_DIR.glob("*.yaml")) if PLAN_DIR.is_dir() else []
    if not paths:
        failures.append("docs/backend-validation must contain at least one YAML plan")
    for path in paths:
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        failures.extend(
            validate_backend_validation_plan(
                payload,
                smoke_records if isinstance(smoke_records, list) else [],
                source=str(path.relative_to(ROOT)),
            )
        )
        if isinstance(payload, dict):
            rendered = render_backend_validation_markdown(payload, str(path.relative_to(ROOT)))
            rendered_path = path.with_suffix(".md")
            if args.write:
                rendered_path.write_text(rendered, encoding="utf-8")
            elif not rendered_path.is_file() or rendered_path.read_text(encoding="utf-8") != rendered:
                failures.append(
                    f"{rendered_path.relative_to(ROOT)} is missing or stale; "
                    "run `uv run python scripts/check_backend_validation.py --write`"
                )
    if failures:
        raise SystemExit("backend validation check failed:\n" + "\n".join(f"- {item}" for item in failures))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
